### ISSUE TITLE
PICKit 5 Fail when programming

### ISSUE THREAD

**Issue by hdhlhs** [callwyat/mplab-extension#19]
Using a PICKit 5 and an ATSAME54N20A, when trying to debug the program VS Code gives the following error:

"Failure to write program to device".

This happens for both mdb and mplabx configurations:
  
```
"configurations": [
        {
            "type": "mdb",
            "request": "launch",
            "name": "Microchip Debug Adapter",
            "filePath": "${workspaceFolder}\\MyProject.X\\dist\\default\\debug\\MyProject.X.debug.elf",
            "device": "ATSAME54N20A",
            "toolType": "pickit5",
            "toolOptions": { },
            "stopOnEntry": true,
            "preLaunchTask": "MPLABX Build"
        },
        {
            "type": "mplabx",
            "request": "launch",
            "name": "MPLABX Debug",
            "program": "${workspaceFolder}/MyProject.X",
            "stopOnEntry": true,
            "preLaunchTask": "MPLABX Build",
            "debug": false,
            "configuration": "default"
        }
```

Debug console output:
```
>Device ATSAME54N20A
HwTool pickit5
>


*****************************************************

Connecting to MPLAB PICkit 5

Currently loaded versions:
Application version...........02.00.84
Boot version..................00.00.10
PCB version...................2
Script version................00.05.85
Script build number...........d33d758f73
Tool pack version ............2.1.245
Target voltage detected
Target device ATSAME54N20A found.
Device Revision Id  = 0x5
Device Id = 0x61840002

>Program "C:\Users\user\Documents\HarmonyProjects\MyProject\firmware\MyProject.X\dist\default\debug\MyProject.X.debug.elf"
Programming target...


*****************************************************

Connecting to MPLAB PICkit 5

Currently loaded versions:
Application version...........02.00.84
Boot version..................00.00.10
PCB version...................2
Script version................00.05.85
Script build number...........d33d758f73
Tool pack version ............2.1.245
Target voltage detected
Target device ATSAME54N20A found.
Device Revision Id  = 0x5
Device Id = 0x61840002

Calculating memory ranges for operation...

Erasing...

The following memory area(s) will be programmed:

```

It seems like it is being programmed twice at the same time. 
Using the MPLABX IDE works fine.
Is there any way to debug this?

**Comment by sachinbarkul** [comment]
Hi 
During debug Project through VSCode error message "Failure to write program to device".
i am tried on ICD3 & ICD4 same issue observed on device PC32MZ2048EFH144.

Launch.json file 

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "mdb",
            "request": "launch",
            "name": "Microchip Debug Adapter",
            "filePath": "${workspaceFolder}\\Firmware_Optimized_BCU_MPLABXV5.30\\ADR245B_V4.03.X\\dist\\default\\production\\ADR245B_V4.03.X.production.hex",
            "device": "PIC32MZ2048EFH144",
            "toolType": "icd3",
            "toolOptions": { },
            "stopOnEntry": true,
            "preLaunchTask": "MPLABX Build"
        },
        {
            "type": "mplabx",
            "request": "launch",
            "name": "MPLABX Debug",
            "program": "${workspaceFolder}\\Firmware_Optimized_BCU_MPLABXV5.30\\ADR245B_V4.03.X",
            "stopOnEntry": true,
            "preLaunchTask": "MPLABX Build",
            "configuration": "default",
            "debug": true
        }
    ]
}

**Comment by callwyat** [comment]
Thanks for submitting this issues. I just released version 0.1.20, and while this release doesn't directly address this issues, it may help. 0.1.20 fixes a problem VSCode would attempt to set breakpoints while programing the device, which may cause issue with programing. Could you two update the extension and let me know if this issue persists?

Thank you!

**Comment by hdhlhs** [comment]
Hello, after updating to the new version 0.1.20 unfortunatly the same issue persists.

**Comment by callwyat** [comment]
Thanks you for checking that!

To answer your original question, yes it is possible to debug this issue to an extent. Simple install `npm` and clone this repository. That should be everything needed in order to build and launch the project. Launching the project will open up an [Extension Development] window of VSCode that you can open any folder with.

If the problem is with the Debug Adapter that I build, you should be able to find the issue in the `mplabxDebug.ts` or `mdbCommunications.ts` files. It is possible the issue is in the Microchip Debugger (MDB) that Microchip provides, but I'm pretty confident that MPLABX uses it as well. My best guess is that this is a programer configuration issue. MPLABX stores these setting in the project file, but I haven't had much success with getting them to work.

Please feel free to poke at it and make a pull request! I would love to put this issue to rest as it pops up every few months and continues to go unresolved.

**Comment by hdhlhs** [comment]
Ok, so for me the issue appears to be the timeout of the programming. In `mdbCommunicataions.ts` in line 404 `query()` is called with a default of 10000 (I'm guessing milliseconds). Increasing that to 100000 fixes the issue. You migth want to make this value adjustable.

**Comment by callwyat** [comment]
That is excellent to hear that you found the source of the problem! I can certainly make a setting to adjust that. Which `query` is timing out? I would guess the `Program` query but I would like to know with more certainty.

**Comment by hdhlhs** [comment]
Exactly, in the programming `query` the flash of the device is first  erased, which takes a few seconds and then programmed, which also takes a few seconds. Apparently this process takes longer than 10 seconds.

**Comment by callwyat** [comment]
Thanks for the information! I have published pre-release version 0.1.21. In this version I have removed the timeouts in favor of using a cancellation event instead. This should fix your issue with timeouts preventing your project from launching! Please test it out when you get a chance and let me know if works, otherwise I'll assume it did and release a non-pre version on Friday.

**Comment by callwyat** [comment]
I have now published v0.1.22, which should address this issue. Please reopen this issue if the problem persists.
